'use client'

import { useState, useMemo } from 'react'
import Link from 'next/link'
import type { Contact } from '@prisma/client'

type SortKey = 'name' | 'role' | 'temperature' | 'trustLevel' | 'company' | 'createdAt'
type SortOrder = 'asc' | 'desc'

export default function ContactsTable({ contacts: initialContacts }: { contacts: Contact[] }) {
  const [contacts, setContacts] = useState(initialContacts)
  const [sortKey, setSortKey] = useState<SortKey>('createdAt')
  const [sortOrder, setSortOrder] = useState<SortOrder>('desc')
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [confirmText, setConfirmText] = useState('')
  const [isDeleting, setIsDeleting] = useState(false)

  // 判断是否为AI生成的人物
  const isAutoGenerated = (contact: Contact) =>
    contact.notes?.includes('自动生成的测试数据') ?? false

  // 排序逻辑
  const sortedContacts = useMemo(() => {
    const sorted = [...contacts].sort((a, b) => {
      let aVal: any, bVal: any

      switch (sortKey) {
        case 'name':
          aVal = a.name; bVal = b.name
          break
        case 'role':
          aVal = a.relationRole; bVal = b.relationRole
          break
        case 'temperature':
          aVal = a.temperature ?? ''; bVal = b.temperature ?? ''
          break
        case 'trustLevel':
          aVal = a.trustLevel ?? 0; bVal = b.trustLevel ?? 0
          break
        case 'company':
          aVal = a.company ?? ''; bVal = b.company ?? ''
          break
        case 'createdAt':
          aVal = a.createdAt?.getTime() ?? 0; bVal = b.createdAt?.getTime() ?? 0
          break
      }

      if (aVal < bVal) return sortOrder === 'asc' ? -1 : 1
      if (aVal > bVal) return sortOrder === 'asc' ? 1 : -1
      return 0
    })
    return sorted
  }, [contacts, sortKey, sortOrder])

  const handleSort = (key: SortKey) => {
    if (sortKey === key) {
      setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc')
    } else {
      setSortKey(key)
      setSortOrder('asc')
    }
  }

  const SortIcon = ({ column }: { column: SortKey }) => {
    if (sortKey !== column) return <span className="text-gray-300">⇅</span>
    return <span>{sortOrder === 'asc' ? '↑' : '↓'}</span>
  }

  // 一键删除所有AI生成数据
  const handleDeleteAllTestData = async () => {
    setIsDeleting(true)
    try {
      const autoGenIds = contacts.filter(isAutoGenerated).map(c => c.id)
      for (const id of autoGenIds) {
        await fetch(`/api/contacts/${id}`, { method: 'DELETE' })
      }
      setContacts(contacts.filter(c => !isAutoGenerated(c)))
      setShowDeleteModal(false)
    } catch (err) {
      console.error('删除失败:', err)
    } finally {
      setIsDeleting(false)
    }
  }

  // 全部删除
  const handleDeleteAll = async () => {
    if (confirmText !== 'confirmdelete') return
    setIsDeleting(true)
    try {
      for (const contact of contacts) {
        await fetch(`/api/contacts/${contact.id}`, { method: 'DELETE' })
      }
      setContacts([])
      setShowDeleteModal(false)
      setConfirmText('')
    } catch (err) {
      console.error('删除失败:', err)
    } finally {
      setIsDeleting(false)
    }
  }

  // 删除单个
  const handleDelete = async (id: string) => {
    try {
      const res = await fetch(`/api/contacts/${id}`, { method: 'DELETE' })
      if (res.ok) {
        setContacts(contacts.filter(c => c.id !== id))
      }
    } catch (err) {
      console.error('删除失败:', err)
    }
  }

  const roleEmoji: Record<string, string> = {
    BIG_INVESTOR: '💰',
    GATEWAY: '🚪',
    ADVISOR: '🧠',
    THERMOMETER: '🌡️',
    LIGHTHOUSE: '🏮',
    COMRADE: '⚔️',
  }

  const roleLabel: Record<string, string> = {
    BIG_INVESTOR: '大金主',
    GATEWAY: '传送门',
    ADVISOR: '智囊',
    THERMOMETER: '温度计',
    LIGHTHOUSE: '灯塔',
    COMRADE: '战友',
  }

  const tempEmoji = (temp: string | null) => {
    if (!temp) return '—'
    return { COLD: '❄️', WARM: '🌤️', HOT: '🔥' }[temp] ?? '—'
  }

  const testDataCount = contacts.filter(isAutoGenerated).length

  return (
    <>
      {contacts.length === 0 ? (
        <div className="p-12 text-center text-gray-400">
          <div className="text-4xl mb-3">📋</div>
          <p className="text-sm">还没有联系人，先去人物标签页新增一位</p>
        </div>
      ) : (
        <>
          {/* 工具栏 */}
          <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between bg-gray-50">
            <div className="text-sm text-gray-600">
              共 {contacts.length} 位联系人
              {testDataCount > 0 && (
                <span className="ml-3 text-gray-500">
                  其中 {testDataCount} 位测试数据
                  <button
                    onClick={handleDeleteAllTestData}
                    className="ml-2 px-2 py-1 text-xs rounded bg-gray-200 text-gray-700 hover:bg-gray-300"
                  >
                    删除全部测试数据
                  </button>
                </span>
              )}
            </div>
            <button
              onClick={() => setShowDeleteModal(true)}
              className="px-3 py-1.5 text-xs rounded border border-rose-300 text-rose-600 hover:bg-rose-50"
            >
              ⚠️ 全部删除
            </button>
          </div>

          {/* 表格 */}
          <table className="w-full text-sm">
            <thead className="bg-gray-50 border-b border-gray-200 text-gray-500">
              <tr>
                <th className="text-right font-medium px-3 py-3 w-16">操作</th>
                <th
                  className="text-left font-medium px-4 py-3 cursor-pointer hover:text-gray-700 select-none"
                  onClick={() => handleSort('name')}
                >
                  姓名 <SortIcon column="name" />
                </th>
                <th
                  className="text-left font-medium px-4 py-3 w-32 cursor-pointer hover:text-gray-700 select-none"
                  onClick={() => handleSort('role')}
                >
                  关系角色 <SortIcon column="role" />
                </th>
                <th className="text-left font-medium px-4 py-3">标签</th>
                <th
                  className="text-center font-medium px-3 py-3 w-20 cursor-pointer hover:text-gray-700 select-none"
                  onClick={() => handleSort('temperature')}
                >
                  温度 <SortIcon column="temperature" />
                </th>
                <th
                  className="text-center font-medium px-3 py-3 w-20 cursor-pointer hover:text-gray-700 select-none"
                  onClick={() => handleSort('trustLevel')}
                >
                  信任度 <SortIcon column="trustLevel" />
                </th>
                <th
                  className="text-left font-medium px-4 py-3 cursor-pointer hover:text-gray-700 select-none"
                  onClick={() => handleSort('company')}
                >
                  公司 <SortIcon column="company" />
                </th>
                <th className="text-left font-medium px-4 py-3">职位</th>
              </tr>
            </thead>
            <tbody>
              {sortedContacts.map((contact) => {
                const tags = contact.tags ? JSON.parse(contact.tags) : []
                const isAuto = isAutoGenerated(contact)
                return (
                  <tr key={contact.id} className="group border-b border-gray-100 hover:bg-gray-50">
                    <td className="px-3 py-3">
                      <div className="flex justify-center items-center gap-1 opacity-0 pointer-events-none group-hover:opacity-100 group-hover:pointer-events-auto transition-opacity">
                        {!isAuto && (
                          <Link
                            href={`/contacts/${contact.id}/edit`}
                            className="px-2 py-1 text-xs rounded border border-gray-200 text-gray-700 hover:bg-gray-50"
                            title="修改"
                          >
                            ✏️
                          </Link>
                        )}
                        <button
                          onClick={() => handleDelete(contact.id)}
                          className="w-6 h-6 text-xs rounded border border-rose-200 text-rose-600 hover:bg-rose-50 flex items-center justify-center"
                          title="删除"
                        >
                          ✕
                        </button>
                      </div>
                    </td>
                    <td className="px-4 py-3 font-medium text-gray-800">
                      {contact.name}
                      {isAuto && <span className="text-red-500 ml-1">*</span>}
                    </td>
                    <td className="px-4 py-3 text-gray-600">
                      <span className="inline-flex items-center gap-1">
                        <span>{roleEmoji[contact.relationRole] || ''}</span>
                        <span>{roleLabel[contact.relationRole] || contact.relationRole}</span>
                      </span>
                    </td>
                    <td className="px-4 py-3 text-gray-600">
                      {tags.length > 0 ? (
                        <div className="flex flex-wrap gap-1">
                          {(tags as string[]).map((tag) => (
                            <span
                              key={tag}
                              className="inline-block px-2 py-0.5 text-xs bg-violet-100 text-violet-700 rounded"
                            >
                              {tag}
                            </span>
                          ))}
                        </div>
                      ) : (
                        <span className="text-gray-400">—</span>
                      )}
                    </td>
                    <td className="px-3 py-3 text-center">
                      {tempEmoji(contact.temperature)}
                    </td>
                    <td className="px-3 py-3 text-center">
                      {contact.trustLevel ? (
                        <span className="text-amber-500">
                          {'★'.repeat(contact.trustLevel)}
                        </span>
                      ) : (
                        <span className="text-gray-400">—</span>
                      )}
                    </td>
                    <td className="px-4 py-3 text-gray-600">
                      {contact.company || '—'}
                    </td>
                    <td className="px-4 py-3 text-gray-600">
                      {contact.title || '—'}
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </>
      )}

      {/* 删除确认模态框 */}
      {showDeleteModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 max-w-md w-full mx-4 shadow-xl">
            <h3 className="text-lg font-bold text-gray-900 mb-4">
              {testDataCount > 0 && confirmText === '' ? '选择删除方式' : '全部删除联系人'}
            </h3>

            {testDataCount > 0 && confirmText === '' ? (
              <div className="space-y-3">
                <p className="text-sm text-gray-600">发现 {testDataCount} 位测试数据</p>
                <div className="space-y-2">
                  <button
                    onClick={handleDeleteAllTestData}
                    disabled={isDeleting}
                    className="w-full px-4 py-2 bg-amber-100 text-amber-700 rounded hover:bg-amber-200 disabled:opacity-50"
                  >
                    只删除测试数据
                  </button>
                  <button
                    onClick={() => setConfirmText('')}
                    className="w-full px-4 py-2 border border-rose-300 text-rose-600 rounded hover:bg-rose-50"
                  >
                    删除全部联系人
                  </button>
                </div>
              </div>
            ) : (
              <div className="space-y-4">
                <p className="text-sm text-red-600 font-medium">
                  ⚠️ 此操作不可撤销，将删除 {contacts.length} 位联系人
                </p>
                <div>
                  <label className="block text-sm text-gray-700 mb-2">
                    请输入 <code className="font-mono text-rose-600">confirmdelete</code> 以确认
                  </label>
                  <input
                    type="text"
                    value={confirmText}
                    onChange={(e) => setConfirmText(e.target.value)}
                    placeholder="confirmdelete"
                    className="w-full px-3 py-2 border border-gray-300 rounded outline-none focus:ring-2 focus:ring-rose-500"
                  />
                </div>
              </div>
            )}

            <div className="flex gap-2 mt-6">
              <button
                onClick={() => {
                  setShowDeleteModal(false)
                  setConfirmText('')
                }}
                className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded hover:bg-gray-50"
              >
                取消
              </button>
              {confirmText !== '' && (
                <button
                  onClick={handleDeleteAll}
                  disabled={isDeleting || confirmText !== 'confirmdelete'}
                  className="flex-1 px-4 py-2 bg-rose-600 text-white rounded hover:bg-rose-700 disabled:opacity-50"
                >
                  {isDeleting ? '删除中…' : '确认删除'}
                </button>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  )
}
